version: '3.9'

services:
  web: 
    build: .  
    image: rag-app
    command: sh -c "GOOGLE_APPLICATION_CREDENTIALS=/app/gemini-api-1234-cdfba0b449d1.json uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    environment:

      - GEMINI_API_KEY=/run/secrets/gemini_api_key.txt 
      - QDRANT_API_KEY=/run/secrets/qdrant_api_key.txt  
    secrets:
      - qdrant_api_key 
      - gemini_api_key  
          
    volumes:
      - ./gemini-api-1234-cdfba0b449d1.json:/app/gemini-api-1234-cdfba0b449d1.json
      - ./secrets:/run/secrets

secrets:
  qdrant_api_key:
    file: ./secrets/qdrant_api_key.txt
  gemini_api_key:
    file: ./secrets/gemini_api_key.txt

